theme = "congo"

baseURL = "https://masoncomputers.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

googleAnalytics = "G-80Y6XJKWK5"


[outputs]
  home = ["HTML", "RSS", "JSON"]
